spring:
  application:
    name: HuiYi-health
  datasource:
    url: jdbc:mysql://localhost:3306/health
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    jwt:
      key: 'abcdefghijklmn'
      expire: 168 # 7 days
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    flow:
      period: 5
      limit: 10000
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#zuoyi:
#  api: ZOE-fe8e5d5b-6f5e-46ca-9a02-c9916ce51f95
